{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          ports:
            - containerPort: {{ .Values.grafana.service.port }}
          volumeMounts:
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-dashboards
          configMap:
            name: {{ .Release.Name }}-grafana-dashboard
            items:
              - key: heart_disease_api_metrics.json
                path: heart_disease_api_metrics.json
        - name: grafana-provisioning-dashboards
          configMap:
            name: {{ .Release.Name }}-grafana-provisioning
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
        - name: grafana-provisioning-datasources
          configMap:
            name: {{ .Release.Name }}-grafana-datasources
            items:
              - key: prometheus.yaml
                path: prometheus.yaml
{{- end }}
